/*
 * pisoCalido — las matas de la tierra caliente (0-2000 msnm).
 *
 * Acá está el hueco de datos más grande de la colección y no se tapa: la CAÑA
 * PANELERA no tiene ficha propia en el repo (ni en `cycle-content/` ni en
 * `grafo-relations.json`) y su lámina lo declara en la cara. Un cuaderno de
 * campo honesto marca lo que no sabe: el vacío señalado es información —
 * dice dónde hay que trabajar. El vacío tapado con adorno es una mentira que
 * alguien va a creer.
 *
 * (Sobre `fuente` / `sinDato`, ver la cabecera de `pisoFrio.js`.)
 */

/* PLÁTANO — la hierba más grande del mundo. */
export const platano = {
  id: 'platano',
  nombre: 'Plátano',
  cientifico: 'Musa × paradisiaca',
  autoridad: 'L.',
  familia: 'Musaceae',
  regionales: ['popocho', 'dominico', 'hartón', 'cachaco', 'comino', 'pelipita', 'manzano', 'topocho'],
  piso: 'calido',
  altitud: [0, 2200],
  altitudOptima: [0, 1800],
  climaNota: 'Por encima de 2000 msnm casi con seguridad no prospera comercialmente. A 1700 crece más despacio y tarda más en dar racimo.',
  alturaM: 6,
  fuente: 'corpus',

  porte: { tipo: 'hierbaGigante', alto: 320, hojas: 6 },
  porteNota: 'HIERBA GIGANTE de 4-8 m — NO ES ÁRBOL. Lo que parece tronco es PSEUDOTALLO: vainas de hoja enrolladas una sobre otra. Por eso se tumba de un machetazo, por eso no tiene corteza y por eso no se poda como árbol. Lo que manda está abajo: el cormo.',
  hoja: {
    forma: 'oblonga',
    borde: 'entero',
    nervadura: 'paralela',
    filotaxia: 'alterna',
    esbeltez: 0.32,
    len: 140,
    fuente: 'corpus-parcial',
    nota: 'Hoja ancha: transpira mucho. Nace enrollada, se abre, y el viento la RASGA entre las venas. Una hoja adulta rasgada NO es una hoja enferma — es una hoja que hizo su trabajo.',
    sinDato: 'El corpus sólo la menciona como "ancha"; forma y nervadura son botánica general.',
  },
  raiz: {
    tipo: 'cormo',
    op: { ancho: 38, alto: 30, hijuelos: 2 },
    fuente: 'corpus',
    nota: 'CORMO (rizoma): tallo subterráneo macizo. De sus yemas salen los HIJUELOS — así se reproduce, porque es clonal desde el siglo XIX (triploide estéril: sin semilla viable). El plátano que usted come no tiene padres, tiene copias.',
  },
  flor: {
    tipo: 'musa',
    op: { largo: 46 },
    color: ['#7a2a44', '#e2c04c'],
    fuente: 'corpus-parcial',
    nota: 'La bellota / chira, con su bráctea morada. Por la inflorescencia entra el moko que llevan los insectos: no es adorno, es una puerta.',
    sinDato: 'El corpus no describe la flor del plátano.',
  },
  fruto: {
    tipo: 'platano',
    op: { largo: 95, ancho: 16 },
    organo: 'racimo',
    color: { piel: '#c9c14a', pulpa: '#f4ecd8' },
    fuente: 'botanica',
    nota: 'El corte TRANSVERSAL es TRILOBADO: tres carpelos. Es la firma de la Musaceae y nadie que haya partido un plátano la olvida.',
  },
  ciclo: [
    { fase: 'siembra', cuando: 'mes 0', nota: 'Colino / hijuelo. Distancia 3×3 a 4×4 m.' },
    { fase: 'deshije', cuando: 'continuo', nota: 'Esquema "1 planta + 1 hijo + 1 nieto": así la cosecha nunca para.' },
    { fase: 'racimo', cuando: 'sin dato', nota: 'El corpus NO da la cifra siembra→racimo.' },
  ],
  cicloFuente: 'corpus-parcial',
  enfermedades: [
    {
      nombre: 'Sigatoka negra',
      folk: ['sigatoka'],
      agente: 'Mycosphaerella fijiensis',
      sintoma: 'sigatoka',
      cara: 'haz',
      gravedad: 'alta',
      senal: 'Empieza como RAYITAS PARDAS finitas que se unen y ENNEGRECEN. Hay que verla EN RAYITA: cuando ya es un parche negro, la hoja no fotosintetiza y el racimo sale chico.',
      manejo: 'Sombra ≥20% baja la severidad de 18% a 13-15%.',
      fuente: 'corpus',
    },
    {
      nombre: 'Moko / madurabiche',
      folk: ['moko', 'madurabiche'],
      agente: 'Ralstonia solanacearum (bacteria)',
      sintoma: 'moko',
      cara: 'organo',
      gravedad: 'alta',
      senal: 'El racimo MADURA PREMATURAMENTE Y POR DENTRO, a veces con exudado y mal olor. Por fuera puede verse bien.',
      alerta: 'Se disemina POR LAS HERRAMIENTAS: el mismo machete lo lleva de mata en mata. Desinfecte. Se erradica la planta ENTERA, cormo incluido.',
      fuente: 'corpus',
    },
    {
      nombre: 'Picudo negro',
      folk: ['picudo', 'gusano tornillo'],
      agente: 'Cosmopolites sordidus',
      sintoma: 'galeriaInterna',
      cara: 'organo',
      gravedad: 'alta',
      senal: 'Galerías DENTRO del cormo. Por fuera: hojas que amarillean y se marchitan, planta que se cae fácil con el viento, y ASERRÍN o residuo café saliendo de la base del pseudotallo.',
      prueba: 'El aserrín en la base es la señal que se ve sin cortar nada: ésa es la que salva el lote.',
      fuente: 'corpus',
    },
  ],
};

/* YUCA — la raíz tuberosa VERDADERA. */
export const yuca = {
  id: 'yuca',
  nombre: 'Yuca',
  cientifico: 'Manihot esculenta',
  autoridad: 'Crantz',
  familia: 'Euphorbiaceae',
  regionales: ['guacamota', 'mandioca', 'yuca brava', 'yuca dulce', 'yuca mansa'],
  notaNombre: 'Dulce/mansa vs BRAVA/amarga: la brava tiene glucósidos cianogénicos y hay que procesarla (casabe). No es un capricho de sabor — es toxicología.',
  piso: 'calido',
  altitud: [0, 1800],
  altitudOptima: [100, 800],
  climaNota: '22-30 °C. Muy sensible al frío: se muere a +8 °C, sin necesidad de helada.',
  alturaM: 3,
  fuente: 'corpus',

  porte: { tipo: 'arbusto', alto: 260, ramas: 3, filo: 'alterna', grosor: 5.5, copa: 0.42 },
  porteNota: 'Arbusto leñoso de 2-4 m.',
  hoja: {
    forma: 'palmatilobada',
    lobulos: 7,
    abertura: 168,
    seno: 0.14, // hendida casi hasta el pecíolo: la firma de la yuca
    anchoLobulo: 0.28,
    borde: 'entero',
    nervadura: 'palmada',
    filotaxia: 'alterna',
    esbeltez: 0.9,
    len: 62,
    peciolo: 'largo, rojizo',
    fuente: 'botanica',
    nota: 'PALMATILOBADA de 5-7 lóbulos lanceolados, hendida casi hasta el pecíolo, sobre un pecíolo largo y rojizo. Es la mano abierta de la yuca: no se confunde con nada.',
    sinDato: 'El corpus describe manchas en la hoja pero no la morfología de la hoja sana.',
  },
  raiz: {
    tipo: 'tuberosaVerdadera',
    op: { cuantas: 5, largo: 74, gordo: 13, abre: 0.78 },
    fuente: 'corpus',
    nota: 'RAÍZ TUBEROSA VERDADERA — el corpus lo distingue expresamente de la papa. NO tiene ojos y NO rebrota: por eso la yuca se siembra de ESTACA de tallo (20-25 cm) y no de raíz. Ponga la papa y la yuca lado a lado y entienda por qué dos matas que "dan un bulto bajo tierra" se manejan al revés.',
  },
  flor: { tipo: 'panicula', op: { alto: 44, ramas: 5, plumosa: true }, color: ['#c9b58a', '#98ab4b'], fuente: 'botanica', sinDato: 'El corpus no documenta la flor de la yuca.' },
  fruto: {
    tipo: 'raizTuberosa',
    op: { rx: 26, ry: 50 },
    organo: 'raíz tuberosa',
    color: { piel: '#7a5238', pulpa: '#f4ecd8' },
    fuente: 'botanica',
    nota: 'En corte: peridermis parda finita, corteza blanca gruesa que se desprende entera cuando está fresca, y el CORDÓN FIBROSO del eje — ése que uno saca al partir la yuca cocida. El cordón es la prueba de que esto es una raíz.',
  },
  ciclo: [
    { fase: 'estaca', cuando: 'mes 0', nota: 'Tallo maduro de 20-25 cm, horizontal o inclinada, a 5-10 cm.' },
    { fase: 'crecimiento', cuando: 'mes 1-7', nota: '' },
    { fase: 'cosecha', cuando: 'mes 8-18', nota: 'Consumo tradicional 8-12. Yuca brava amazónica: 12-18.' },
  ],
  cicloFuente: 'corpus',
  enfermedades: [
    {
      nombre: 'Cochinilla harinosa',
      folk: ['cochinilla', 'piojo blanco'],
      agente: 'Pseudococcidae',
      sintoma: 'cochinilla',
      cara: 'organo',
      gravedad: 'media',
      senal: 'HILOS y ALGODÓN BLANCO CEROSO en el tallo y la yema. Debajo de la cera hay un cuerpo blando: ése es el bicho. Suele haber hormigas pastoreándola por la melaza.',
      alerta: 'La NEGRILLA negra que crece encima es fumagina sobre la melaza: NO ataca el tejido. Se quita controlando la cochinilla, no con fungicida.',
      fuente: 'corpus',
    },
    {
      nombre: 'Mancha foliar',
      folk: ['mancha'],
      agente: 'hongo o bacteria — sin identificar en el corpus',
      sintoma: 'manchaAngular',
      cara: 'haz',
      gravedad: 'media',
      senal: 'Aquí se aplica LA REGLA DE LECTURA: si la mancha tiene BORDE DEFINIDO con HALO AMARILLO → hongo (tipo Cercospora). Si es DIFUSA y ACUOSA → bacteriosis.',
      cuando: 'En lluvia, no en sol.',
      fuente: 'corpus',
    },
  ],
};

/* CACAO — el cauliflor. */
export const cacao = {
  id: 'cacao',
  nombre: 'Cacao',
  cientifico: 'Theobroma cacao',
  autoridad: 'L.',
  familia: 'Malvaceae',
  regionales: [],
  notaNombre: '*Theobroma* = "alimento de los dioses". El corpus no registra sinónimos regionales.',
  piso: 'calido',
  altitud: [0, 1200],
  altitudOptima: [200, 900],
  climaNota: '22-28 °C. Muy sensible al frío: +10 °C ya lo mata.',
  alturaM: 6,
  fuente: 'corpus',

  porte: { tipo: 'arbol', alto: 300, copaR: 0.4, ramas: 4, cauliflor: true },
  porteNota: 'Árbol de 4-8 m, CAULIFLOR: las flores y las mazorcas nacen DIRECTAMENTE SOBRE EL TRONCO y las ramas viejas, en cojines florales que producen año tras año. Por eso el machete NO va ahí: cada cojín cortado es cosecha perdida por años.',
  hoja: {
    forma: 'oblonga',
    borde: 'entero',
    nervadura: 'pinnada',
    filotaxia: 'alterna',
    esbeltez: 0.3,
    len: 120,
    fuente: 'botanica',
    nota: 'Hoja grande y oblonga. La hoja NUEVA sale ROJIZA y COLGANTE, como un trapo mojado, y después se endereza y verdea. Eso es normal — no es enfermedad.',
    sinDato: 'El corpus no documenta la hoja del cacao.',
  },
  raiz: { tipo: 'pivotante', op: { hondo: 100, grosor: 4.4 }, fuente: 'botanica', sinDato: 'El corpus no documenta la raíz del cacao.' },
  flor: {
    tipo: 'cauliflora',
    op: { r: 8 },
    color: ['#fbf6e8', '#e8c766'],
    fuente: 'corpus',
    nota: 'Diminuta, sobre el tronco. Tan chica y tan rara que sólo la poliniza un jején minúsculo (Forcipomyia), no la abeja: de cada mil flores cuajan tres.',
  },
  fruto: {
    tipo: 'mazorcaCacao',
    op: { rx: 32, ry: 52, surcos: 10 },
    organo: 'mazorca',
    color: { piel: '#c9722f', pulpa: '#f2efe4' },
    fuente: 'corpus',
    nota: 'En corte: las semillas en el MUCÍLAGO blanco, sobre la placenta central. Lo que se fermenta 5-7 días en cajón de madera son ESAS semillas CON su baba: sin baba no hay fermentación, y sin fermentación no hay chocolate — sólo semilla amarga. El sabor se decide después de cosechar.',
  },
  ciclo: [
    { fase: 'semilla', cuando: 'mes 0', nota: 'RECALCITRANTE: pierde viabilidad en 1-2 semanas si se seca. No se guarda.' },
    { fase: 'injerto', cuando: 'mes 6-12', nota: 'Sobre patrón franco.' },
    { fase: 'primera cosecha', cuando: 'año 2-3', nota: 'Injertado. De semilla: 3-5 años.' },
    { fase: 'fermentación', cuando: 'día 5-7 poscosecha', nota: 'En cajones de madera. Define el perfil de sabor.' },
  ],
  cicloFuente: 'corpus',
  enfermedades: [
    {
      nombre: 'Monilia',
      folk: ['monilia', 'moniliasis'],
      agente: 'Moniliophthora roreri',
      sintoma: 'monilia',
      cara: 'organo',
      gravedad: 'alta',
      senal: 'Empieza como MANCHAS ACEITOSAS oscuras en el fruto joven — AHÍ todavía se puede cortar y enterrar. Después: pudrición interna con CAPA POLVORIENTA BLANQUECINA, como harina.',
      alerta: 'Se lleva el 40% de la producción nacional si no se maneja. Cada mazorca enferma dejada en el suelo siembra el lote entero.',
      fuente: 'corpus',
    },
    {
      nombre: 'Escoba de bruja',
      folk: ['escoba'],
      agente: 'Moniliophthora perniciosa',
      sintoma: 'escobaDeBruja',
      cara: 'organo',
      gravedad: 'alta',
      senal: 'La rama forma un MANOJO DENSO de brotes deformados, ENGROSADOS, con ENTRENUDOS CORTOS — cara de escoba vieja. Después se seca.',
      alerta: 'NO cura con fungicida. Es poda fitosanitaria y nada más. El engrose se ve ANTES de que se seque: ahí es cuando hay que cortar.',
      fuente: 'corpus',
    },
  ],
};

/* CAÑA PANELERA — el hueco de datos declarado. */
export const cana = {
  id: 'cana-panelera',
  nombre: 'Caña panelera',
  cientifico: 'Saccharum officinarum',
  autoridad: 'L.',
  familia: 'Poaceae',
  regionales: [],
  piso: 'calido',
  altitud: [0, 1900],
  altitudOptima: [0, 1500],
  climaNota: 'La Hoya del Río Suárez (Santander/Boyacá, 1200-1900 msnm) es la de mayor tradición: las noches frescas concentran la sacarosa.',
  alturaM: 3.5,
  fuente: 'corpus-parcial',

  /* LA ADVERTENCIA VA EN LA LÁMINA, en la cara, no en un pie de página. */
  hueco: {
    titulo: 'Lámina incompleta — y lo dice',
    texto:
      'La caña panelera NO tiene ficha en este repositorio: ni en cycle-content/ ni en grafo-relations.json. Es el hueco de datos más grande de las 21 láminas. Lo que sigue sale del corpus de piso térmico (altitud y ciclo) y de botánica general (morfología). Sus ENFERMEDADES no están documentadas en ninguna fuente del repo — por eso esta lámina no tiene panel de señales. Un cuaderno honesto marca lo que le falta: este vacío es una tarea, no un defecto.',
  },

  porte: { tipo: 'graminea', alto: 300, nudos: 8, zancudas: false, grosor: 6 },
  porteNota: 'Macolla de tallos gruesos. Botánica general: el corpus no describe el porte.',
  hoja: {
    forma: 'lineal',
    borde: 'entero',
    nervadura: 'paralela',
    filotaxia: 'disticha',
    esbeltez: 0.1,
    len: 150,
    fuente: 'botanica',
    sinDato: 'El corpus no documenta la hoja de la caña.',
  },
  raiz: { tipo: 'macolla', op: { hijos: 4, largo: 54 }, fuente: 'botanica', nota: 'Cepa que rebrota: de ahí sale la soca.', sinDato: 'El corpus no documenta la raíz.' },
  flor: { tipo: 'panicula', op: { alto: 80, ramas: 8, plumosa: true }, color: ['#d8c9a6', '#bcc6ac'], fuente: 'botanica', nota: 'Panícula plumosa, plateada.', sinDato: 'El corpus no documenta la flor.' },
  fruto: {
    tipo: 'cana',
    op: { largo: 140, ancho: 19, nudos: 6 },
    organo: 'tallo',
    color: { piel: '#98ab4b', pulpa: '#e6dcb4' },
    fuente: 'botanica',
    nota: 'El azúcar está en el parénquima del ENTRENUDO. En corte transversal los haces se ven como puntos REGADOS, sin anillos — es monocotiledónea: no tiene anillos de crecimiento como el tronco de un árbol. En cada NUDO hay una yema: de ahí rebrota la soca y de ahí sale la semilla vegetativa.',
  },
  ciclo: [
    { fase: 'siembra', cuando: 'mes 0', nota: 'Trozo de tallo con yemas.' },
    { fase: 'primer corte', cuando: 'mes 12-18', nota: '' },
    { fase: 'socas', cuando: 'años siguientes', nota: 'Rebrota con ciclos más cortos, varios años antes de resembrar.' },
  ],
  cicloFuente: 'corpus',
  enfermedades: [],
  sinDato: [
    'NINGUNA enfermedad de la caña está documentada en el corpus del repo.',
    'Morfología (raíz, hoja, flor, altura) tampoco: todo lo de esta lámina es botánica general declarada.',
  ],
};

/* AHUYAMA — la monoica rastrera. */
export const ahuyama = {
  id: 'ahuyama',
  nombre: 'Ahuyama',
  cientifico: 'Cucurbita moschata',
  autoridad: 'Duchesne',
  familia: 'Cucurbitaceae',
  regionales: ['auyama', 'zapallo', 'calabaza'],
  notaNombre: 'OJO — son DOS especies: C. moschata = auyama/ahuyama (cálido, 0-2200, cuello largo). C. maxima = zapallo/calabaza (altura, 1000-2600, panza redonda, hasta 50 kg). El corpus las separa; el mercado las revuelve.',
  piso: 'calido',
  altitud: [0, 2200],
  altitudOptima: [200, 1800],
  climaNota: 'C. moschata aguanta más calor y humedad que C. maxima.',
  alturaM: 0.5,
  fuente: 'corpus',

  porte: { tipo: 'rastrera', largo: 320, nodos: 5 },
  porteNota: 'Rastrera de guías largas. "Cubre el suelo con sus hojas amplias y reduce la evapotranspiración": por eso va de compañera — no es que sobre espacio, es que el suelo tapado se seca menos.',
  hoja: {
    forma: 'palmatilobada',
    lobulos: 5,
    abertura: 150,
    seno: 0.62, // lóbulos SOMEROS: al revés que la yuca
    anchoLobulo: 0.62,
    borde: 'crenado',
    nervadura: 'palmada',
    filotaxia: 'alterna',
    esbeltez: 1,
    len: 62,
    fuente: 'corpus-parcial',
    nota: 'Hoja AMPLIA, palmatilobada de lóbulos SOMEROS (la yuca los tiene profundos: compárelas) y borde festoneado. El corpus sólo dice "hojas amplias".',
  },
  raiz: { tipo: 'pivotante', op: { hondo: 70, grosor: 3 }, fuente: 'botanica', sinDato: 'El corpus no documenta la raíz de la ahuyama.' },
  flor: {
    tipo: 'cucurbitacea',
    op: { r: 18 },
    color: ['#f2c33a', '#e2c04c'],
    fuente: 'corpus',
    nota: 'MONOICA: macho y hembra separadas EN LA MISMA MATA. La hembra trae la ahuyamita ya puesta debajo de la flor (ovario ínfero); el macho va en pedúnculo largo y desnudo. Aprender a distinguirlas responde el "botó la flor y no cargó": las que botó eran los machos, y eso es normal.',
    cocina: 'Las flores MASCULINAS se cosechan temprano en la mañana y se rellenan con queso o huevo — patrimonio culinario de Cundinamarca y Boyacá. Cosechar machos no cuesta cosecha.',
  },
  fruto: {
    tipo: 'cucurbita',
    op: { rx: 44, ry: 40, gajos: 8, cuello: true },
    organo: 'fruto',
    color: { piel: '#c9922f', pulpa: '#e79a2b' },
    fuente: 'corpus',
    nota: 'C. moschata: cuello largo o piriforme, piel verde-ocre que vira a amarillo-crema al madurar, CARNE ANARANJADA INTENSA. C. maxima: 3-15 kg (los gigantes, hasta 50), pulpa amarillo-anaranjada.',
  },
  ciclo: [
    { fase: 'siembra', cuando: 'mes 0', nota: 'Directa, 2-3 semillas por hoyo.' },
    { fase: 'guía', cuando: 'mes 1-2', nota: '' },
    { fase: 'floración', cuando: 'mes 2-3', nota: 'Primero los machos. No se asuste.' },
    { fase: 'cosecha', cuando: 'mes 4-5', nota: 'Cuando la guía se marchita. C. maxima: 4-6.' },
  ],
  cicloFuente: 'corpus',
  enfermedades: [
    {
      nombre: 'Mildeo velloso',
      folk: ['mildeo'],
      agente: 'Pseudoperonospora cubensis',
      sintoma: 'mildeoVelloso',
      cara: 'enves',
      gravedad: 'alta',
      senal: 'AMARILLENTO EN EL HAZ + VELLOSIDAD GRIS-MORADA EN EL ENVÉS.',
      cuando: 'Clima fresco muy húmedo.',
      alerta: 'NO lo confunda con el OÍDIO: ése es POLVO BLANCO SECO EN EL HAZ, sin vellosidad, y se limpia con el dedo. Se tratan distinto — por eso van los dos en esta lámina.',
      fuente: 'corpus',
    },
    {
      nombre: 'Oídio',
      folk: ['ceniza', 'polvo blanco'],
      agente: 'Erysiphaceae',
      sintoma: 'oidio',
      cara: 'haz',
      gravedad: 'media',
      senal: 'POLVO BLANCO SECO en el HAZ. Se limpia con el dedo. Sin halo amarillo, sin vellosidad.',
      fuente: 'corpus',
    },
  ],
};

/* AGUACATE — el de raíz superficial. */
export const aguacate = {
  id: 'aguacate',
  nombre: 'Aguacate',
  cientifico: 'Persea americana',
  autoridad: 'Mill.',
  familia: 'Lauraceae',
  regionales: ['cura', 'palta', 'aguacatillo'],
  piso: 'calido',
  altitud: [0, 2500],
  altitudOptima: [1700, 2200],
  climaNota: 'Hass comercial 1700-2400: las noches frescas le engruesan la cáscara y le suben el aceite. El criollo aguanta por debajo de 1000.',
  alturaM: 8,
  fuente: 'corpus',

  porte: { tipo: 'arbol', alto: 310, copaR: 0.44, ramas: 4 },
  porteNota: 'Perenne, 3-30 m según manejo y patrón.',
  hoja: {
    forma: 'eliptica',
    borde: 'entero',
    nervadura: 'pinnada',
    filotaxia: 'alterna',
    esbeltez: 0.34,
    len: 100,
    coriacea: true,
    fuente: 'botanica',
    nota: 'Elíptica, coriácea, ALTERNA. Compárela con el café, que es OPUESTA: esa sola diferencia separa los dos a diez metros.',
    sinDato: 'El corpus no documenta la hoja del aguacate.',
  },
  raiz: {
    tipo: 'superficial',
    op: { ancho: 115, hondo: 32, cuantas: 9 },
    fuente: 'corpus',
    nota: 'RAÍZ SUPERFICIAL — el corpus lo dice y es la clave del cultivo: se AHOGA con el encharcamiento. Exige drenaje excelente. Dibujarla honda sería recomendar mal y matar árboles.',
  },
  flor: {
    tipo: 'lauracea',
    op: { r: 9 },
    color: ['#c9d68a', '#e8c766'],
    fuente: 'corpus',
    nota: 'Chica y verdoso-amarilla. Su gracia no es la forma sino la DICOGAMIA tipo A / tipo B: abren a horas distintas del día para no autopolinizarse. Por eso se siembran MEZCLADOS — un lote de un solo tipo carga poco y nadie entiende por qué.',
  },
  fruto: {
    tipo: 'drupaAguacate',
    op: { rx: 32, ry: 46 },
    organo: 'baya',
    color: { piel: '#3f5b25', pulpa: '#c9d68a' },
    fuente: 'corpus',
    nota: 'La semilla ocupa medio fruto, con sus dos cotiledones y su tegumento papeloso. Hass: cáscara gruesa y rugosa.',
  },
  ciclo: [
    { fase: 'injerto', cuando: 'mes 0', nota: 'Hass sobre patrón.' },
    { fase: 'primera producción', cuando: 'año 3-4', nota: 'Injertado. El criollo de semilla tarda más.' },
    { fase: 'producción plena', cuando: 'año 5-6', nota: '' },
  ],
  cicloFuente: 'corpus',
  enfermedades: [
    {
      nombre: 'Pudrición radicular',
      folk: ['la marchitez', 'pudrición'],
      agente: 'Phytophthora cinnamomi',
      sintoma: 'pudricionRadicular',
      cara: 'organo',
      gravedad: 'alta',
      senal: 'Raíz NECRÓTICA OSCURA y DESPRENDIBLE — se deshace entre los dedos. Arriba: hojas caídas y árbol que se apaga.',
      cuando: 'Exceso de riego, mal drenaje.',
      manejo: 'Trichoderma + sombrío de guamo reduce 70% (según ficha del repo).',
      fuente: 'corpus',
    },
    {
      nombre: 'Negrilla / fumagina',
      folk: ['negrilla', 'hollín'],
      agente: 'Capnodium spp.',
      sintoma: 'fumagina',
      cara: 'haz',
      gravedad: 'baja',
      senal: 'Capa NEGRA tipo HOLLÍN sobre la hoja.',
      alerta: 'NO ataca el tejido: crece sobre la MELAZA de los chupadores (pulgón, mosca blanca, escama). Se resuelve controlando el INSECTO. El fungicida acá es plata botada.',
      fuente: 'corpus',
    },
    {
      nombre: 'Roña / sarna',
      folk: ['roña', 'sarna'],
      agente: 'Sphaceloma perseae',
      sintoma: 'ronia',
      cara: 'organo',
      gravedad: 'baja',
      senal: 'Pintitas ÁSPERAS tipo sarna en la CÁSCARA.',
      alerta: 'Superficial y estética: GENERALMENTE NO COMPROMETE LA PULPA. Va en esta lámina justamente para que no se fumigue por gusto — la lámina que enseña a NO hacer nada vale igual que la que alarma.',
      fuente: 'corpus',
    },
  ],
};

export const PISO_CALIDO = [platano, yuca, cacao, cana, ahuyama, aguacate];
