/*
 * pisoTemplado — las matas de la tierra templada (1000-2800 msnm).
 *
 * Es la franja donde vive la mayoría de los campesinos andinos y donde se
 * cruzan casi todos los cultivos: el café manda, pero el maíz y el frijol lo
 * acompañan desde antes de que el café existiera en América. Ver esas tres
 * láminas juntas es ver la economía de una ladera colombiana.
 *
 * (Sobre la procedencia de cada dato — `fuente`, `sinDato` — ver la cabecera
 * de `pisoFrio.js`: la regla es la misma y no se repite.)
 */

/* CAFÉ — el que paga el año. */
export const cafe = {
  id: 'cafe',
  nombre: 'Café',
  cientifico: 'Coffea arabica',
  autoridad: 'L.',
  familia: 'Rubiaceae',
  regionales: ['caturra', 'Castillo®', 'Cenicafé 1', 'típica', 'borbón'],
  notaNombre: 'Son VARIEDADES, no nombres regionales: en Colombia el café se nombra por variedad.',
  piso: 'templado',
  altitud: [1000, 2200],
  altitudOptima: [1200, 1800],
  climaNota: '18-24 °C, 1600-2800 mm de lluvia al año. Sombra parcial 35-50%.',
  alturaM: 2.5,
  fuente: 'corpus',

  porte: { tipo: 'arbusto', alto: 250, ramas: 5, filo: 'opuesta', grosor: 5, copa: 0.6 },
  porteNota: 'Un eje que sube (ortotrópico) y bandolas que cargan (plagiotrópicas). Esa diferencia ES el manejo: el eje se zoquea, las bandolas producen una vez y no repiten.',

  hoja: {
    forma: 'acuminada',
    borde: 'ondulado',
    nervadura: 'broquidodroma', // LA firma
    filotaxia: 'opuesta', // la otra firma
    esbeltez: 0.36,
    len: 92,
    lustrosa: true,
    fuente: 'corpus+botanica',
    nota: 'Hojas OPUESTAS, lustrosas, acuminadas (punta de goteo) y de nervadura BROQUIDÓDROMA: las venas se unen en bucles antes del borde. Esas dos cosas identifican un cafeto sin ver un solo fruto.',
  },

  raiz: {
    tipo: 'pivotante',
    op: { hondo: 92, grosor: 4, nodulos: false },
    fuente: 'botanica',
    sinDato: 'El corpus no documenta la raíz del café.',
  },

  flor: {
    tipo: 'rubiacea',
    op: { r: 12 },
    color: ['#fbf6e8', '#e7c24a'],
    fuente: 'corpus+botanica',
    nota: 'Blanca, 5 pétalos, en glomérulos sobre la axila. Dispara con DÉFICIT HÍDRICO PREVIO + LLUVIA — no con la lluvia sola: ése es el error común. Alguna caída de flor es normal (autoaborto); caída masiva CON manchas es alarma.',
  },

  fruto: {
    tipo: 'drupaCafe',
    op: { r: 36 },
    organo: 'cereza (drupa)',
    color: { piel: '#c23227', pulpa: '#e07f66' },
    fuente: 'corpus+botanica',
    nota: 'Verde → rojo al madurar. Adentro, casi siempre DOS granos cara a cara, cada uno en su pergamino, con la baba (mucílago) alrededor. Cada capa tiene su paso: despulpado quita la pulpa, lavado quita la baba, trillado quita el pergamino. La lámina es el mapa del beneficio.',
  },

  ciclo: [
    { fase: 'germinador', cuando: 'mes 0-2', nota: 'En arena.' },
    { fase: 'almácigo', cuando: 'mes 2-6', nota: 'Embolsado antes de trasplantar.' },
    { fase: 'floración', cuando: 'año 2+', nota: 'Tras déficit hídrico + lluvia.' },
    { fase: 'cosecha', cuando: '8 meses tras florecer', nota: 'Principal sep-ene; mitaca abr-jun (lluvias bimodales).' },
  ],
  cicloFuente: 'corpus',

  enfermedades: [
    {
      nombre: 'Roya',
      folk: ['roya'],
      agente: 'Hemileia vastatrix',
      sintoma: 'roya',
      cara: 'enves',
      gravedad: 'alta',
      senal: 'POLVO FINO AMARILLO-NARANJA en el ENVÉS — se le pega en los dedos, como polvo de azafrán. En el haz sólo se ve una mancha amarilla pálida: quien mira sólo el haz llega tarde. VOLTEE LA HOJA.',
      cuando: 'No es de aquí: llegó de África en el siglo XX.',
      fuente: 'corpus',
    },
    {
      nombre: 'Ojo de gallo',
      folk: ['gotera', 'candelilla', 'viruela'],
      agente: 'Mycena citricolor',
      sintoma: 'ojoDeGallo',
      cara: 'haz',
      gravedad: 'media',
      senal: 'Mancha REDONDA con un PUNTICO en el centro; después bota un cuerpo gelatinoso como una gota.',
      cuando: 'Exceso de sombra y humedad. Ésta sí es nativa de América.',
      alerta: 'Le dicen "viruela", pero la viruela de la mora es ANTRACNOSIS: mismo apodo, otra enfermedad, otro manejo.',
      fuente: 'corpus',
    },
    {
      nombre: 'Broca',
      folk: ['broca'],
      agente: 'Hypothenemus hampei',
      sintoma: 'broca',
      cara: 'organo',
      gravedad: 'alta',
      senal: 'Escarabajo negro del tamaño de una cabeza de alfiler. Perfora el fruto POR LA CORONA — el huequito está ahí y en ninguna otra parte. Adentro, galerías en la almendra.',
      umbral: 'Cenicafé: actuar sobre 2% de frutos infestados, con la mitad en posición A/B.',
      fuente: 'corpus',
    },
  ],
  sinDato: ['Mancha de hierro (Cercospora coffeicola) aparece nombrada — favorecida por sol directo sin sombra — pero sin descripción de la lesión.'],
};

/* MAÍZ — el más viejo. */
export const maiz = {
  id: 'maiz',
  nombre: 'Maíz',
  cientifico: 'Zea mays',
  autoridad: 'L.',
  familia: 'Poaceae',
  regionales: ['maíz criollo', 'capio', 'pira', 'cusco', 'negro de páramo'],
  notaNombre: 'Capio, Pira, Cusco y Negro de Páramo son patrimonio muisca — no "variedades viejas".',
  piso: 'templado',
  altitud: [0, 3200],
  altitudOptima: [1000, 2600],
  climaNota: '15-24 °C. La helada lo mata a −1 °C.',
  alturaM: 2.4,
  fuente: 'corpus',

  porte: { tipo: 'graminea', alto: 280, nudos: 6, zancudas: true, grosor: 4.4 },
  porteNota: 'Del primer nudo salen RAÍCES ZANCUDAS (fúlcreas): son las que lo paran contra el viento. El aporque las entierra — por eso se aporca el maíz.',

  hoja: {
    forma: 'lineal',
    borde: 'entero',
    nervadura: 'paralela',
    filotaxia: 'disticha',
    esbeltez: 0.13,
    len: 150,
    fuente: 'corpus',
    nota: 'Nervadura PARALELA — el corpus lo dice al derecho: "la hoja de gramínea se rasga naturalmente a lo largo de esas venas". Dos hileras y nada más (dística): la gramínea no tiene otra opción.',
  },

  raiz: {
    tipo: 'fasciculada',
    op: { cuantas: 15, largo: 70, grosor: 1.7, abre: 1.2 },
    fuente: 'botanica',
    nota: 'Manojo sin eje que mande. Explora arriba y se seca primero: el maíz sufre la sequía antes que el frijol que tiene al lado.',
    sinDato: 'El corpus no enuncia el tipo de raíz del maíz.',
  },

  flor: {
    tipo: 'panicula',
    op: { alto: 70, ramas: 7 },
    color: ['#c9b58a', '#e2c04c'],
    fuente: 'botanica',
    nota: 'MONOICO: la espiga macho arriba (el penacho) suelta el polen al viento; la mazorca hembra va en la axila y saca los ESTIGMAS (los cabellos). CADA CABELLO ES UN GRANO: si ese cabello no recibe polen, ese grano no sale. Por eso la mazorca sale desgranada — y por eso el maíz se siembra en bloque, nunca en fila sola.',
    sinDato: 'El corpus no describe la inflorescencia: la morfología es botánica general.',
  },

  fruto: {
    tipo: 'mazorca',
    op: { largo: 105, ancho: 27, hileras: 10 },
    organo: 'mazorca',
    color: { piel: '#e2c04c', pulpa: '#f0e2c0' },
    fuente: 'corpus',
    nota: 'Capio: 12-18 cm, 8-12 hileras, grano amarillo-naranja HARINOSO (endospermo blando). Negro de Páramo: grano morado-negro por antocianinas. Las hileras son SIEMPRE PARES: cada espiguilla trae dos flores.',
  },

  ciclo: [
    { fase: 'siembra', cuando: 'día 0', nota: 'Directa.' },
    { fase: 'cogollo', cuando: 'día 20-40', nota: 'La fase que el cogollero espera.' },
    { fase: 'floración', cuando: 'día 55-70', nota: 'Penacho y cabellos.' },
    { fase: 'choclo', cuando: 'día 70-100', nota: 'ICA V-109 en cálido: 70-80 días.' },
    { fase: 'grano seco', cuando: 'día 120-170', nota: 'Los andinos de altura: 6-9 meses (Capio 6-8, Negro de Páramo 7-9).' },
  ],
  cicloFuente: 'corpus',

  enfermedades: [
    {
      nombre: 'Cogollero',
      folk: ['cogollero', 'gusano del cogollo'],
      agente: 'Spodoptera frugiperda',
      sintoma: 'cogollero',
      cara: 'haz',
      gravedad: 'alta',
      senal: 'Daño en el COGOLLO (las hojas nuevas enrolladas). Al desenrollar la hoja aparecen HUECOS ALINEADOS EN FILA — salen en fila porque la larva mordió la hoja enrollada y atravesó todas las vueltas de un golpe. Aserrín de excremento a la vista: si está fresco, la larva está adentro AHORA.',
      fuente: 'corpus',
    },
    {
      nombre: 'Carbón del maíz',
      folk: ['carbón', 'huitlacoche'],
      agente: 'Ustilago maydis',
      sintoma: 'carbon',
      cara: 'organo',
      gravedad: 'media',
      senal: 'AGALLAS gris-blancas en la mazorca, en lugar de los granos. Revientan y sueltan POLVO NEGRO.',
      alerta: 'Tierna y cerrada es el huitlacoche, que se come y se vende caro. Reventada ya no: sólo siembra esporas.',
      fuente: 'corpus',
    },
    {
      nombre: 'Mancha de asfalto',
      folk: ['asfalto'],
      agente: 'complejo Phyllachora maydis',
      sintoma: 'manchaAsfalto',
      cara: 'haz',
      gravedad: 'media',
      senal: 'Puntos negros pequeños, ABULTADOS, incrustados en el tejido y regados al azar.',
      prueba: 'Fróteles con el dedo: NO se desprenden. Eso los separa de cualquier suciedad o del polvo de otra cosa.',
      fuente: 'corpus',
    },
  ],
  sinDato: ['Pudrición de mazorca por Fusarium (pudrición rosada-anaranjada interna) está mencionada sin más detalle.'],
};

/* FRIJOL — el que le da de comer al maíz. */
export const frijol = {
  id: 'frijol',
  nombre: 'Fríjol',
  cientifico: 'Phaseolus vulgaris',
  autoridad: 'L.',
  familia: 'Fabaceae',
  regionales: ['cargamanto', 'bola roja', 'radical', 'quimbaya', 'ICA-Bachué'],
  piso: 'templado',
  altitud: [0, 2800],
  altitudOptima: [1500, 2400],
  climaNota: '14-30 °C; vegetativo 18-28 °C; floración y llenado de vaina 20-24 °C.',
  alturaM: 2,
  fuente: 'corpus',

  porte: { tipo: 'trepadora', alto: 250, vueltas: 3.6, nodos: 7, filo: 'alterna', tutorAncho: 22 },
  porteNota: 'Voluble (trepador) o arbustivo según variedad. El voluble usa el MAÍZ de tutor: por eso van sembrados juntos, y por eso el frijol le devuelve nitrógeno al maíz. No es folclor, es contabilidad.',

  hoja: {
    compuesta: 'trifoliolada',
    formaFoliolo: 'ovada',
    borde: 'entero',
    nervadura: 'pinnada',
    filotaxia: 'alterna',
    esbeltez: 0.62,
    len: 74,
    fuente: 'botanica',
    nota: 'TRIFOLIOLADA: tres foliolos, el terminal con su peciolulo y los laterales asimétricos. Es la hoja que la mancha angular encajona entre las venas.',
    sinDato: 'El corpus no documenta la hoja del fríjol.',
  },

  raiz: {
    tipo: 'pivotante',
    op: { hondo: 82, grosor: 2.8, nodulos: true },
    fuente: 'corpus',
    nota: 'Fija nitrógeno con Rhizobium. NÓDULOS ROSADOS por dentro = fijación activa. GRISES = fijación fallida. Se rajan con la uña y se sabe al instante si la simbiosis está trabajando.',
  },

  flor: { tipo: 'papilionacea', op: { r: 11 }, color: ['#fbf6e8', '#d8b8d0'], fuente: 'botanica', sinDato: 'El corpus no documenta la flor.' },

  fruto: {
    tipo: 'vaina',
    op: { largo: 92, ancho: 11, granos: 5, curva: 0.14 },
    organo: 'vaina',
    color: { piel: '#8aa34e', pulpa: '#c23227' },
    fuente: 'corpus',
    nota: 'Bola Roja: grano grande, esférico, rojo brillante.',
  },

  ciclo: [
    { fase: 'siembra', cuando: 'mes 0', nota: 'Asociado con maíz, al empezar las lluvias.' },
    { fase: 'floración', cuando: 'mes 1.5-2.5', nota: '20-24 °C o se cae la flor.' },
    { fase: 'cosecha', cuando: 'mes 3-4', nota: 'Arbustivo.' },
    { fase: 'cosecha (voluble)', cuando: 'mes 5-7', nota: 'Bola Roja. En seco, vainas marchitas, desvainado a mano.' },
  ],
  cicloFuente: 'corpus',

  enfermedades: [
    {
      nombre: 'Antracnosis',
      folk: ['antracnosis'],
      agente: 'Colletotrichum lindemuthianum',
      sintoma: 'antracnosis',
      cara: 'organo',
      gravedad: 'alta',
      senal: 'Manchas HUNDIDAS oscuras en la VAINA, de borde bien definido y CENTRO ROSADO-SALMÓN (son las esporas).',
      alerta: 'SE TRANSMITE POR SEMILLA: no guarde semilla de planta enferma, por buena que se vea la vaina sana de al lado.',
      fuente: 'corpus',
    },
    {
      nombre: 'Mancha angular',
      folk: ['mancha angular'],
      agente: 'Pseudocercospora griseola',
      sintoma: 'manchaAngular',
      cara: 'haz',
      gravedad: 'media',
      senal: 'Lesiones ANGULARES, con esquinas: la nervadura las encajona y no las deja redondearse. Si es redonda, no es ésta.',
      alerta: 'También se transmite por semilla.',
      fuente: 'corpus',
    },
  ],
};

/* ARRACACHA — la Apiaceae andina. */
export const arracacha = {
  id: 'arracacha',
  nombre: 'Arracacha',
  cientifico: 'Arracacia xanthorrhiza',
  autoridad: 'Bancr.',
  familia: 'Apiaceae',
  regionales: ['racacha', 'apio criollo', 'zanahoria blanca'],
  piso: 'templado',
  altitud: [1500, 3200],
  altitudOptima: [1800, 2800],
  alturaM: 0.9,
  fuente: 'corpus',

  porte: { tipo: 'herbacea', alto: 180, nodos: 7, filo: 'roseta', grosor: 4 },
  porteNota: 'Mata en roseta: las hojas salen todas de la corona, no de un tallo.',
  hoja: {
    compuesta: 'imparipinnada',
    pares: 2,
    formaFoliolo: 'ovada',
    borde: 'aserrado',
    nervadura: 'pinnada',
    filotaxia: 'roseta',
    esbeltez: 0.6,
    len: 82,
    fuente: 'botanica',
    nota: 'Apiaceae: la misma familia de la zanahoria, el apio y el perejil — y se le nota en la hoja pinnada de borde aserrado y en el pecíolo envainador. Huélala: huele a apio.',
    sinDato: 'El corpus no documenta la hoja; la forma es la típica de Apiaceae, declarada como tal.',
  },
  raiz: {
    tipo: 'tuberosaVerdadera',
    op: { cuantas: 4, largo: 70, gordo: 12, abre: 0.7 },
    fuente: 'corpus',
    nota: 'RAÍZ TUBEROSA VERDADERA (15-25 cm, 200-800 g): la raíz misma engruesa. NO es tubérculo: no tiene ojos y no rebrota. Por eso se siembra de HIJUELO de la corona y nunca de semilla.',
  },
  flor: {
    tipo: 'umbela',
    op: { r: 30, radios: 9, compuesta: true },
    color: ['#d8c9a6', '#6d5946'],
    fuente: 'botanica',
    nota: 'Umbela compuesta, como toda Apiaceae.',
    sinDato: 'El corpus no documenta la flor de la arracacha.',
  },
  fruto: {
    tipo: 'raizTuberosa',
    op: { rx: 28, ry: 48 },
    organo: 'raíz tuberosa',
    color: { piel: '#c9a06a', pulpa: '#e8c766' },
    fuente: 'corpus',
    nota: "'Amarilla': pulpa amarilla intensa (mucho β-caroteno). 'Blanca': marfil. 'Morada': violácea por antocianinas.",
  },
  ciclo: [
    { fase: 'siembra', cuando: 'mes 0', nota: 'Hijuelo del cuello, en hoyo de 30 cm.' },
    { fase: 'aporque', cuando: 'mes 4', nota: '' },
    { fase: 'cosecha', cuando: 'mes 10-14', nota: 'Ciclo largo — hay fichas que dicen 8-12.' },
  ],
  cicloFuente: 'corpus',
  enfermedades: [
    {
      nombre: 'Insecto de suelo',
      folk: ['gusano de la raíz'],
      agente: 'no identificado en el corpus',
      sintoma: 'galeriaInterna',
      cara: 'organo',
      gravedad: 'media',
      senal: 'Raíz RAJADA con hueco interno comido. Si los bordes del hueco se ponen blandos y húmedos, hay un hongo secundario aprovechando la herida — la herida vino primero.',
      fuente: 'corpus',
    },
  ],
  sinDato: ['Pudrición de corona (Sclerotium rolfsii) y pudrición blanda (Erwinia carotovora) aparecen sólo nombradas, sin descripción visual.'],
};

/* CEBOLLA LARGA — la de Aquitania. */
export const cebollaLarga = {
  id: 'cebolla-larga',
  nombre: 'Cebolla larga',
  cientifico: 'Allium fistulosum',
  autoridad: 'L.',
  familia: 'Amaryllidaceae',
  regionales: ['cebollín', 'cebolla junca'],
  notaNombre: '*fistulosum* = "hecha un tubo". El nombre científico ES la clave de campo.',
  piso: 'templado',
  altitud: [800, 3500],
  altitudOptima: [1800, 2800],
  alturaM: 0.6,
  fuente: 'corpus',
  lugar: 'Aquitania, Boyacá — la orilla del lago de Tota.',

  porte: { tipo: 'herbacea', alto: 150, nodos: 5, filo: 'disticha', grosor: 5 },
  hoja: {
    forma: 'lineal',
    borde: 'entero',
    nervadura: 'paralela',
    filotaxia: 'disticha',
    esbeltez: 0.07,
    len: 130,
    tubular: true,
    fuente: 'corpus',
    nota: 'HOJA TUBULAR HUECA — el corpus lo dice y es EL carácter: se dobla y se seca de punta a base con viento o sequía. Es lo que la separa de la cabezona.',
  },
  raiz: {
    tipo: 'macolla',
    op: { hijos: 3, largo: 46 },
    fuente: 'corpus',
    nota: 'Se multiplica por DIVISIÓN DE MACOLLOS, no por bulbo verdadero ni por semilla. Cada 4 meses se divide y se vuelve a sembrar: cosecha permanente.',
  },
  flor: {
    tipo: 'globosa',
    op: { r: 17 },
    color: ['#efe7d8', '#c9b58a'],
    fuente: 'botanica',
    sinDato: 'En fase comercial normalmente no florece (eso sí lo dice el corpus): la umbela globosa es botánica general.',
  },
  fruto: {
    tipo: 'tubo',
    op: { r: 22 },
    organo: 'hoja tubular',
    color: { piel: '#63a447', pulpa: '#f4ecd8' },
    fuente: 'corpus',
    nota: 'Lo que se cosecha es la hoja. En corte transversal se ve el HUECO: eso es fistulosum.',
  },
  ciclo: [
    { fase: 'división', cuando: 'mes 0', nota: 'Bulbillos separados de la macolla.' },
    { fase: 'cosecha', cuando: 'mes 4', nota: 'Y otra vez, y otra: es perenne.' },
  ],
  cicloFuente: 'corpus',
  enfermedades: [
    {
      nombre: 'Trips',
      folk: ['trips'],
      agente: 'Thrips tabaci',
      sintoma: 'trips',
      cara: 'haz',
      gravedad: 'media',
      senal: 'RASPADO plateado o bronceado sobre la hoja. El bicho es diminuto y alargado.',
      fuente: 'corpus',
    },
    {
      nombre: 'Mildeo velloso',
      folk: ['mildeo'],
      agente: 'Peronospora destructor',
      sintoma: 'mildeoVelloso',
      cara: 'enves',
      gravedad: 'alta',
      senal: 'Manchas AMARILLENTAS ALARGADAS que siguen el largo de la hoja tubular, con VELLOSIDAD GRIS-MORADA encima cuando hay humedad.',
      cuando: 'Tras varios días seguidos de rocío o lluvia.',
      fuente: 'corpus',
    },
  ],
};

/* TOMATE — el de invernadero. */
export const tomate = {
  id: 'tomate',
  nombre: 'Tomate',
  cientifico: 'Solanum lycopersicum',
  autoridad: 'L.',
  familia: 'Solanaceae',
  regionales: ['chonto', 'milano', 'cherry', 'uvalina'],
  piso: 'templado',
  altitud: [0, 2900],
  altitudOptima: [1500, 2500],
  climaNota: '16-28 °C según variedad. En Colombia va sobre todo bajo invernadero.',
  alturaM: 1.8,
  fuente: 'corpus',

  porte: { tipo: 'herbacea', alto: 240, nodos: 7, filo: 'alterna', grosor: 3.6 },
  porteNota: 'DETERMINADO (San Marzano): para de crecer y concentra la cosecha. INDETERMINADO (cherry, Sungold): no para nunca — pide tutorado colgado y poda de chupones toda la vida. Elegir mal es condenarse a un trabajo que no se quería.',
  hoja: {
    compuesta: 'imparipinnada',
    pares: 3,
    intercalares: true,
    formaFoliolo: 'ovada',
    borde: 'aserrado',
    nervadura: 'pinnada',
    filotaxia: 'alterna',
    esbeltez: 0.5,
    len: 88,
    pubescente: true,
    fuente: 'botanica',
    nota: 'Imparipinnada de foliolos desiguales con foliolillos intercalados, borde aserrado, pubescente glandular — es la que suelta el olor a tomate cuando se roza.',
    sinDato: 'El corpus no documenta la hoja del tomate.',
  },
  raiz: { tipo: 'pivotante', op: { hondo: 80, grosor: 3 }, fuente: 'botanica', sinDato: 'El corpus no documenta la raíz.' },
  flor: { tipo: 'solanacea', op: { r: 13, reflexo: true }, color: ['#f4c542', '#e2c04c'], fuente: 'botanica', nota: 'Amarilla, con los pétalos reflejados hacia atrás y el cono de anteras al frente.', sinDato: 'El corpus no documenta la flor.' },
  fruto: {
    tipo: 'baya',
    op: { rx: 36, ry: 32, loculos: 3, semillasPorLoculo: 8 },
    organo: 'baya',
    color: { piel: '#c23227', pulpa: '#e08a63' },
    fuente: 'botanica',
    nota: 'Baya con lóculos de gel y semillas pardas.',
  },
  ciclo: [
    { fase: 'siembra', cuando: 'día 0', nota: '' },
    { fase: 'floración', cuando: 'día 45-60', nota: '' },
    { fase: 'primera cosecha', cuando: 'día 90-120', nota: '' },
    { fase: 'producción', cuando: 'mes 6-9', nota: 'Los indeterminados, bajo invernadero.' },
  ],
  cicloFuente: 'corpus',
  enfermedades: [
    {
      nombre: 'Virus del enrollamiento amarillo',
      folk: ['la cuchara', 'virus'],
      agente: 'transmitido por mosca blanca (Bemisia tabaci)',
      sintoma: 'virusEnrollamiento',
      cara: 'haz',
      gravedad: 'alta',
      senal: 'La hoja se ENROSCA HACIA ARRIBA en forma de CUCHARA, amarillea con veteado de mosaico, y la planta queda ENANA.',
      alerta: 'NO CURA. Se erradica la planta. Lo que se controla es la mosca blanca, no el virus.',
      fuente: 'corpus',
    },
    {
      nombre: 'Minador de la hoja',
      folk: ['minador', 'dibujante'],
      agente: 'Liriomyza spp.',
      sintoma: 'minador',
      cara: 'haz',
      gravedad: 'media',
      senal: 'GALERÍAS SERPENTEANTES blancas DENTRO de la hoja (entre las dos capas), que se ENSANCHAN a medida que avanzan: la larva crece mientras come. La galería se lee como un reloj.',
      fuente: 'corpus',
    },
    {
      nombre: 'Marchitez vascular / nematodo',
      folk: ['marchitez', 'nudo de la raíz'],
      agente: 'Fusarium oxysporum · Ralstonia · Meloidogyne',
      sintoma: 'anilloVascular',
      cara: 'organo',
      gravedad: 'alta',
      senal: 'Corte el tallo por la base: ANILLO OSCURO CAFÉ por dentro. Si además hay NUDOS como perlitas en la raíz, es nematodo.',
      prueba: 'Nematodo: la mata se marchita a mediodía y AMANECE PARADA. Ese vaivén es la pista.',
      fuente: 'corpus',
    },
  ],
};

/* TOMATE DE ÁRBOL — el mejor documentado del corpus. */
export const tomateDeArbol = {
  id: 'tomate-de-arbol',
  nombre: 'Tomate de árbol',
  cientifico: 'Solanum betaceum',
  autoridad: 'Cav.',
  familia: 'Solanaceae',
  regionales: ['tomate de palo', 'tamarillo', 'chupitá'],
  piso: 'templado',
  altitud: [1200, 3000],
  altitudOptima: [1800, 2500],
  alturaM: 3,
  fuente: 'corpus',
  notaFuente: 'Es, por lejos, el cultivo con mejor cobertura morfológica en el corpus: hoja, flor, fruto en corte y hábito están descritos. Sirve de patrón de "fuente fuerte" para el resto de la colección.',

  porte: { tipo: 'arbusto', alto: 250, ramas: 4, filo: 'alterna', grosor: 6, copa: 0.5 },
  porteNota: 'Arbolito perenne semileñoso de copa redondeada, 2-4 m. Crece rápido y vive poco: 4-8 años productivos y se acabó.',
  hoja: {
    forma: 'acorazonada',
    borde: 'entero',
    nervadura: 'pinnada',
    filotaxia: 'alterna',
    esbeltez: 0.78,
    len: 96,
    pubescente: true,
    fuente: 'corpus',
    nota: 'Hojas ALTERNAS, grandes, ACORAZONADAS, PUBESCENTES, verde grisáceo. Todo esto sí está en el corpus, palabra por palabra.',
  },
  raiz: {
    tipo: 'pivotante',
    op: { hondo: 74, grosor: 3.4 },
    fuente: 'corpus-parcial',
    nota: 'Susceptible a nematodos y a exceso de humedad.',
    sinDato: 'El tipo exacto de raíz no está en el corpus.',
  },
  flor: {
    tipo: 'solanacea',
    op: { r: 12 },
    color: ['#f0d8e4', '#f4c542'],
    fuente: 'corpus',
    nota: 'Flores pequeñas ROSA-BLANCAS con ANTERAS AMARILLAS, en cimas axilares. Descrito en el corpus.',
  },
  fruto: {
    tipo: 'baya',
    op: { rx: 30, ry: 44, loculos: 2, semillasPorLoculo: 12, ovoide: true },
    organo: 'baya ovoide',
    color: { piel: '#a83a2e', pulpa: '#e08a63' },
    fuente: 'corpus',
    nota: 'Baya ovoide de 5-10 cm. Pulpa jugosa con semillas pardas en gel. Cultivar naranja: gel TRANSLÚCIDO, pulpa anaranjada. Cultivar morado: gel MORADO-VIOLETA intenso (antocianinas) y pulpa anaranjada profunda.',
  },
  ciclo: [
    { fase: 'germinación', cuando: 'día 21-30', nota: 'A 18-22 °C.' },
    { fase: 'vivero', cuando: 'mes 6-12', nota: 'O injerto, que acorta.' },
    { fase: 'fructificación', cuando: 'mes 8-12', nota: 'Desde la siembra.' },
    { fase: 'plena producción', cuando: 'año 2', nota: 'Y hasta el año 4-8: se acaba rápido.' },
  ],
  cicloFuente: 'corpus',
  enfermedades: [
    {
      nombre: 'Antracnosis',
      folk: ['antracnosis'],
      agente: 'Colletotrichum spp.',
      sintoma: 'antracnosis',
      cara: 'organo',
      gravedad: 'alta',
      senal: 'Manchitas HUNDIDAS oscuras en la fruta que SE AGRANDAN DESPUÉS DE COSECHADO.',
      alerta: 'La infección ya venía del campo, latente. La fruta salió "sana" del lote y se pudre en la caja: no fue el transporte.',
      fuente: 'corpus',
    },
  ],
};

/* UCHUVA — la del farolillo. */
export const uchuva = {
  id: 'uchuva',
  nombre: 'Uchuva',
  cientifico: 'Physalis peruviana',
  autoridad: 'L.',
  familia: 'Solanaceae',
  regionales: ['guchuva', 'uvilla'],
  piso: 'templado',
  altitud: [1200, 3200],
  altitudOptima: [1800, 2800],
  alturaM: 1.2,
  fuente: 'corpus',
  lugar: 'Colombia es el principal exportador del mundo.',

  porte: { tipo: 'herbacea', alto: 210, nodos: 6, filo: 'alterna', grosor: 3.4 },
  porteNota: 'Arbusto perenne, pero de vida corta: 2-3 años productivos. Pide tutorado.',
  hoja: {
    forma: 'acorazonada',
    borde: 'sinuado',
    nervadura: 'pinnada',
    filotaxia: 'alterna',
    esbeltez: 0.76,
    len: 72,
    pubescente: true,
    fuente: 'botanica',
    sinDato: 'El corpus no documenta la hoja de la uchuva.',
  },
  raiz: { tipo: 'pivotante', op: { hondo: 66, grosor: 2.6 }, fuente: 'botanica', sinDato: 'El corpus no documenta la raíz.' },
  flor: {
    tipo: 'campanulada',
    op: { r: 12 },
    color: ['#e2c04c', '#4a2c48'],
    fuente: 'botanica',
    nota: 'Campana amarilla con MÁCULAS MORADAS en la garganta: la guía de néctar que ve el polinizador y que nosotros casi no miramos.',
    sinDato: 'El corpus no documenta la flor.',
  },
  fruto: {
    tipo: 'farolillo',
    op: { r: 24 },
    organo: 'baya en cáliz',
    color: { piel: '#e79a2b', pulpa: '#e2c04c' },
    fuente: 'corpus',
    nota: 'CÁLIZ PAPIRÁCEO que envuelve la baya naranja — el corpus lo dice así. Ese farol es el empaque que le puso la mata: por eso viaja a Europa sin refrigerar. La uchuva trae su propia caja.',
  },
  ciclo: [
    { fase: 'siembra', cuando: 'mes 0', nota: 'Por semilla.' },
    { fase: 'floración', cuando: 'mes 4-5', nota: '' },
    { fase: 'cosecha', cuando: 'mes 8-10', nota: 'Ciclo productivo.' },
  ],
  cicloFuente: 'corpus',
  enfermedades: [
    {
      nombre: 'Polilla / minador',
      folk: ['polilla', 'minador'],
      agente: 'Tuta absoluta · Liriomyza huidobrensis',
      sintoma: 'minador',
      cara: 'haz',
      gravedad: 'media',
      senal: 'Galerías en la hoja.',
      fuente: 'corpus-parcial',
      sinDato: 'El corpus NOMBRA las dos plagas para uchuva pero no describe el daño en esta especie. El dibujo sigue el patrón del tomate (misma familia) y se declara como analogía, no como dato.',
    },
  ],
};

/* MORA — la de Castilla. */
export const mora = {
  id: 'mora',
  nombre: 'Mora',
  cientifico: 'Rubus glaucus',
  autoridad: 'Benth.',
  familia: 'Rosaceae',
  regionales: ['mora de Castilla', 'mora castellana', 'mora andina', 'zarzamora'],
  notaNombre: '*glaucus* = por el envés BLANCO-AZULADO de la hoja. Otra vez: el nombre científico es la clave de campo.',
  piso: 'templado',
  altitud: [1500, 2800],
  altitudOptima: [1800, 2600],
  alturaM: 2,
  fuente: 'corpus',

  porte: { tipo: 'trepadora', alto: 240, vueltas: 2.2, nodos: 6, filo: 'alterna', tutorAncho: 30 },
  porteNota: 'Cañas sobre ESPALDERA. La silvestre tiene espinas; el cultivar comercial no. La caña carga una vez y se corta: se maneja renovando cañas, no podando ramas.',
  hoja: {
    compuesta: 'trifoliolada',
    formaFoliolo: 'ovada',
    borde: 'aserrado',
    nervadura: 'pinnada',
    filotaxia: 'alterna',
    esbeltez: 0.6,
    len: 76,
    envesGlauco: true,
    fuente: 'botanica',
    nota: 'Trifoliolada, borde bien aserrado, y el ENVÉS BLANCO-AZULADO (glauco) que le da el nombre. Voltee la hoja: si el envés es blanco, es mora de Castilla.',
    sinDato: 'El corpus no documenta la hoja.',
  },
  raiz: { tipo: 'fasciculada', op: { cuantas: 12, largo: 58, grosor: 1.6 }, fuente: 'botanica', sinDato: 'El corpus no documenta la raíz.' },
  flor: { tipo: 'rosacea', op: { r: 12 }, color: ['#fbf6e8', '#e2c04c'], fuente: 'botanica', sinDato: 'El corpus no documenta la flor.' },
  fruto: {
    tipo: 'polidrupa',
    op: { rx: 24, ry: 30, drupeolas: 24 },
    organo: 'polidrupa',
    color: { piel: '#3b1e33', pulpa: '#7a2a44' },
    fuente: 'botanica',
    nota: 'Fruto AGREGADO: un montón de drupéolas, cada una con su semillita. Por eso se magulla — no tiene una cáscara, tiene cien. El receptáculo se queda EN LA MATA al cosechar (la frambuesa sale hueca; la mora no).',
  },
  ciclo: [
    { fase: 'acodo', cuando: 'mes 0', nota: 'Acodo de punta o esqueje.' },
    { fase: 'primera cosecha', cuando: 'mes 8-10', nota: 'Cultivar sin espinas. La silvestre: 2 años.' },
    { fase: 'vida útil', cuando: 'año 5-8', nota: 'Renovando cañas.' },
  ],
  cicloFuente: 'corpus',
  enfermedades: [
    {
      nombre: 'Antracnosis',
      folk: ['viruela'],
      agente: 'Colletotrichum spp.',
      sintoma: 'antracnosis',
      cara: 'organo',
      gravedad: 'alta',
      senal: 'Manchas HUNDIDAS oscuras en el fruto.',
      alerta: 'Le dicen "viruela", pero NO es el ojo de gallo del café — que también llaman viruela. Mismo apodo, dos enfermedades, dos manejos. El corpus advierte esto expresamente.',
      fuente: 'corpus',
    },
  ],
};

export const PISO_TEMPLADO = [cafe, maiz, frijol, arracacha, cebollaLarga, tomate, tomateDeArbol, uchuva, mora];
