# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

#  fileSystems."/" =
#    { device = "/dev/disk/by-uuid/2f0fc112-f105-4d20-b6ca-3212f9562304";
#      fsType = "ext4";
#    };

#  fileSystems."/boot" =
##    { device = "/dev/disk/by-uuid/9265-2B1F";
#      fsType = "vfat";
#      options = [ "fmask=0022" "dmask=0022" ];
##    };

##  fileSystems."/mnt/data" =
#    { device = "tank";
#      fsType = "zfs";
#    };

#  fileSystems."/mnt/data/backups" =
#    { device = "tank/backups";
#      fsType = "zfs";
#    };

#  fileSystems."/mnt/data/immich" =
#    { device = "tank/immich";
#      fsType = "zfs";
##    };

#  fileSystems."/mnt/data/media" =
#    { device = "tank/media";
#      fsType = "zfs";
#    };

#  fileSystems."/mnt/fast" =
#    { device = "tank-fast";
#      fsType = "zfs";
#    };

#  fileSystems."/mnt/fast" =
#    { device = "/dev/disk/by-uuid/214A-D5E0";
#      fsType = "vfat";
#      options = [ "fmask=0022" "dmask=0022" ];
#    };

##  swapDevices =
#    [ { device = "/dev/disk/by-uuid/f1210d16-0fae-40fa-b8c2-b74995ee89d4"; }
#    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.br-63bc85014f7c.useDHCP = lib.mkDefault true;
  # networking.interfaces.br-667f5a7ae5a8.useDHCP = lib.mkDefault true;
  # networking.interfaces.docker0.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp3s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
