/* Fachada pública de clima y vestuario por especie. */
export {
  CUERPO_NEUTRO,
  PERFIL_ABEJA,
  PERFIL_ANGELITA,
  PERFIL_COLIBRI,
  PERFIL_OSO,
  PERFIL_RANA,
  PERFIL_JAGUAR,
  PERFIL_OSO_BASTON,
  PERFIL_ZARIGUYA,
  PERFIL_LUCIERNAGA,
  PERFIL_CHIVITO,
  PERFIL_CHIVITO_PUNK,
  PERFIL_GUACAMAYA,
  PERFILES,
  PERFILES_COMPAI,
  cuerpoDeClima,
  ROPA_PERFIL_POR_BICHO,
  ROPA_PERFIL_DEFECTO,
  ROPA_NEUTRA,
  ropaDeClima,
  ropaDeClimaBicho,
  ropaPerfilDeBicho,
} from '../creatureClimaCuerpo.js';
