import { Droplets, FlaskConical, Leaf, RotateCcw, Shovel, Sparkles, Wheat } from 'lucide-react';

export const BASE_SOIL_LIFE = 48;

export const mundoSubsueloDecisions = [
  {
    id: 'compost-bocashi',
    title: 'Compost y bocashi',
    icon: Leaf,
    effect: 14,
    tone: 'good',
    guide: 'Lombricita',
    result: 'Comida suave para lombrices, microbios y raices.',
    why: 'La materia organica alimenta la vida del suelo y ayuda a formar una tierra mas esponjosa.',
    achievement: 'Logro: Despertaste comida para la red viva',
  },
  {
    id: 'cobertura',
    title: 'Cubrir el suelo',
    icon: Wheat,
    effect: 10,
    tone: 'good',
    guide: 'Lombricita',
    result: 'La lluvia entra mas despacio y la tierra se mantiene fresca.',
    why: 'La cobertura protege contra golpe de lluvia, sol fuerte y erosion.',
    achievement: 'Logro: Pusiste cobija a la tierra',
  },
  {
    id: 'no-labrar',
    title: 'No labrar',
    icon: Shovel,
    effect: 9,
    tone: 'good',
    guide: 'Miquito',
    result: 'Las hifas siguen conectadas como caminos finos bajo la finca.',
    why: 'Mover menos el suelo conserva tuneles, raices viejas y redes de hongos beneficos.',
    achievement: 'Logro: Cuidaste el internet de los hongos',
  },
  {
    id: 'micorriza',
    title: 'Inocular micorriza',
    icon: Sparkles,
    effect: 12,
    tone: 'good',
    guide: 'Miquito',
    result: 'La red de hongos conecta plantas y mueve agua y nutrientes.',
    why: 'Las micorrizas viven junto a las raices. La planta entrega azucares y el hongo ayuda a explorar el suelo.',
    achievement: 'Logro: Despertaste la red de hongos',
  },
  {
    id: 'rotacion',
    title: 'Rotar cultivos',
    icon: RotateCcw,
    effect: 8,
    tone: 'good',
    guide: 'Miquito',
    result: 'Cada cultivo deja raices distintas y rompe ciclos de problemas.',
    why: 'Rotar y asociar diversifica alimentos para el suelo y reduce presion repetida de plagas.',
    achievement: 'Logro: La finca cambio de ritmo',
  },
  {
    id: 'biopreparado',
    title: 'Biopreparado especifico',
    icon: FlaskConical,
    effect: 7,
    tone: 'good',
    guide: 'Lombricita',
    result: 'Apoyo puntual sin apagar toda la vida del suelo.',
    why: 'En Chagra se prefieren biopreparados con uso especifico, diluidos y aplicados con cuidado.',
    achievement: 'Logro: Elegiste ayuda con medida',
  },
  {
    id: 'labranza-intensa',
    title: 'Labranza intensa',
    icon: Shovel,
    effect: -16,
    tone: 'bad',
    guide: 'Miquito',
    result: 'La red se rompio y el agua corre por encima.',
    why: 'Remover mucho rompe tuneles, deja el suelo desnudo y puede aumentar erosion.',
    achievement: 'Alerta: La red se rompio y el agua corre por encima',
  },
  {
    id: 'exceso-quimico',
    title: 'Exceso quimico',
    icon: Droplets,
    effect: -18,
    tone: 'bad',
    guide: 'Lombricita',
    result: 'Las raices quedan cortas y la tierra pierde aliados.',
    why: 'El exceso de insumos fuertes puede bajar la actividad biologica. Mejor diagnosticar y aplicar lo necesario.',
    achievement: 'Alerta: La tierra pidio descanso',
  },
];
