// DO NOT EDIT — generated by openapi-typescript

export interface paths {}
export interface operations {}

/** JSON:API relationship reference */
interface JsonApiRelationshipData {
  id: string;
  type: string;
}

/** Generic JSON:API relationship */
interface JsonApiRelationship {
  data: JsonApiRelationshipData | JsonApiRelationshipData[] | null;
}

/** Common JSON:API links */
interface JsonApiLinks {
  self?: string;
}

export interface components {
  schemas: {
    // -------------------------------------------------------------------------
    // Assets
    // -------------------------------------------------------------------------

    "asset--plant": {
      id: string;
      type: "asset--plant";
      attributes: {
        name: string;
        status: "active" | "archived";
        notes: string | null;
        land_name: string | null;
        /** ISO 8601 date when the plant was created */
        created: string | null;
        /** ISO 8601 date of last modification */
        changed: string | null;
        /** Whether the asset is intrinsically a location */
        is_location: boolean;
        /** Whether the asset is a fixed location */
        is_fixed: boolean;
      };
      relationships: {
        plant_type?: JsonApiRelationship;
        location?: JsonApiRelationship;
        image?: JsonApiRelationship;
        file?: JsonApiRelationship;
        [key: string]: JsonApiRelationship | undefined;
      };
      links?: JsonApiLinks;
    };

    "asset--structure": {
      id: string;
      type: "asset--structure";
      attributes: {
        name: string;
        status: "active" | "archived";
        notes: string | null;
        created: string | null;
        changed: string | null;
        is_location: boolean;
        is_fixed: boolean;
      };
      relationships: {
        location?: JsonApiRelationship;
        image?: JsonApiRelationship;
        file?: JsonApiRelationship;
        [key: string]: JsonApiRelationship | undefined;
      };
      links?: JsonApiLinks;
    };

    "asset--equipment": {
      id: string;
      type: "asset--equipment";
      attributes: {
        name: string;
        status: "active" | "archived";
        notes: string | null;
        /** Serial number or manufacturer code */
        manufacturer: string | null;
        model: string | null;
        serial_number: string | null;
        created: string | null;
        changed: string | null;
        is_location: boolean;
        is_fixed: boolean;
      };
      relationships: {
        location?: JsonApiRelationship;
        image?: JsonApiRelationship;
        file?: JsonApiRelationship;
        [key: string]: JsonApiRelationship | undefined;
      };
      links?: JsonApiLinks;
    };

    "asset--land": {
      id: string;
      type: "asset--land";
      attributes: {
        name: string;
        status: "active" | "archived";
        notes: string | null;
        /** WKT or GeoJSON geometry string for geolocation */
        intrinsic_geometry: string | null;
        /** Land type (field, bed, greenhouse, etc.) */
        land_type: string | null;
        created: string | null;
        changed: string | null;
        is_location: boolean;
        is_fixed: boolean;
      };
      relationships: {
        location?: JsonApiRelationship;
        image?: JsonApiRelationship;
        file?: JsonApiRelationship;
        [key: string]: JsonApiRelationship | undefined;
      };
      links?: JsonApiLinks;
    };

    "asset--material": {
      id: string;
      type: "asset--material";
      attributes: {
        name: string;
        status: "active" | "archived";
        notes: string | null;
        /** Material type (compost, seed, fertilizer, etc.) */
        material_type: string | null;
        created: string | null;
        changed: string | null;
        is_location: boolean;
        is_fixed: boolean;
      };
      relationships: {
        location?: JsonApiRelationship;
        image?: JsonApiRelationship;
        file?: JsonApiRelationship;
        [key: string]: JsonApiRelationship | undefined;
      };
      links?: JsonApiLinks;
    };

    // -------------------------------------------------------------------------
    // Logs
    // -------------------------------------------------------------------------

    "log--harvest": {
      id: string;
      type: "log--harvest";
      attributes: {
        name: string;
        /** Unix timestamp of the log event */
        timestamp: number | null;
        status: "pending" | "done";
        notes: string | null;
        quantity: Array<{
          measure: string | null;
          value: string | null;
          unit: string | null;
          label: string | null;
        }> | null;
        created: string | null;
        changed: string | null;
      };
      relationships: {
        asset?: JsonApiRelationship;
        location?: JsonApiRelationship;
        category?: JsonApiRelationship;
        image?: JsonApiRelationship;
        file?: JsonApiRelationship;
        [key: string]: JsonApiRelationship | undefined;
      };
      links?: JsonApiLinks;
    };

    "log--seeding": {
      id: string;
      type: "log--seeding";
      attributes: {
        name: string;
        timestamp: number | null;
        status: "pending" | "done";
        notes: string | null;
        quantity: Array<{
          measure: string | null;
          value: string | null;
          unit: string | null;
          label: string | null;
        }> | null;
        created: string | null;
        changed: string | null;
      };
      relationships: {
        asset?: JsonApiRelationship;
        location?: JsonApiRelationship;
        category?: JsonApiRelationship;
        image?: JsonApiRelationship;
        file?: JsonApiRelationship;
        [key: string]: JsonApiRelationship | undefined;
      };
      links?: JsonApiLinks;
    };

    "log--input": {
      id: string;
      type: "log--input";
      attributes: {
        name: string;
        timestamp: number | null;
        status: "pending" | "done";
        notes: string | null;
        quantity: Array<{
          measure: string | null;
          value: string | null;
          unit: string | null;
          label: string | null;
        }> | null;
        created: string | null;
        changed: string | null;
      };
      relationships: {
        asset?: JsonApiRelationship;
        location?: JsonApiRelationship;
        category?: JsonApiRelationship;
        material?: JsonApiRelationship;
        image?: JsonApiRelationship;
        file?: JsonApiRelationship;
        [key: string]: JsonApiRelationship | undefined;
      };
      links?: JsonApiLinks;
    };

    "log--maintenance": {
      id: string;
      type: "log--maintenance";
      attributes: {
        name: string;
        timestamp: number | null;
        status: "pending" | "done";
        notes: string | null;
        created: string | null;
        changed: string | null;
      };
      relationships: {
        asset?: JsonApiRelationship;
        location?: JsonApiRelationship;
        category?: JsonApiRelationship;
        image?: JsonApiRelationship;
        file?: JsonApiRelationship;
        [key: string]: JsonApiRelationship | undefined;
      };
      links?: JsonApiLinks;
    };

    "log--observation": {
      id: string;
      type: "log--observation";
      attributes: {
        name: string;
        timestamp: number | null;
        status: "pending" | "done";
        notes: string | null;
        /** Whether this observation log records a movement */
        is_movement: boolean;
        created: string | null;
        changed: string | null;
      };
      relationships: {
        asset?: JsonApiRelationship;
        location?: JsonApiRelationship;
        category?: JsonApiRelationship;
        image?: JsonApiRelationship;
        file?: JsonApiRelationship;
        [key: string]: JsonApiRelationship | undefined;
      };
      links?: JsonApiLinks;
    };

    // -------------------------------------------------------------------------
    // Taxonomy terms
    // -------------------------------------------------------------------------

    "taxonomy_term--plant_type": {
      id: string;
      type: "taxonomy_term--plant_type";
      attributes: {
        name: string;
        description: string | null;
      };
      relationships: {
        [key: string]: JsonApiRelationship | undefined;
      };
      links?: JsonApiLinks;
    };

    "taxonomy_term--log_category": {
      id: string;
      type: "taxonomy_term--log_category";
      attributes: {
        name: string;
      };
      relationships: {
        [key: string]: JsonApiRelationship | undefined;
      };
      links?: JsonApiLinks;
    };
  };
}
