# modules/observability/default.nix
# =============================================================================
# OBSERVABILITY DOMAIN — Time-series data & monitoring
# Includes: InfluxDB, Grafana, Telegraf
# =============================================================================

{ config, pkgs, lib, ... }:

let
  cfg = config.guatoc.observability;
  registry = import ../../lib/registry.nix { inherit lib; };
in
{
  imports = [
    ./influxdb.nix
    ./grafana.nix
    ./logging.nix
  ];

  # ============================================
  # OPTIONS: Feature toggles for the domain
  # ============================================
  options.guatoc.observability = {
    enable = lib.mkEnableOption "Observability - Time series & monitoring" // {
      default = false;
    };
    
    # Submodules (logging, influxdb, grafana) handle their own enable options
  };

  # ============================================
  # CONFIG: Apply when observability.enable = true
  # ============================================
  config = lib.mkIf cfg.enable {
    # Note: Telegraf se configura directamente en hosts/alpha/default.nix
    # Note: User/group creation and directories are handled by the legacy modules

    # Ensure sanoid package is installed
    environment.systemPackages = [ pkgs.sanoid ];

    # --- SANOID: ZFS Snapshots ---
    # Create /etc/sanoid directory via tmpfiles.d
    systemd.tmpfiles.rules = [
      "d /etc/sanoid 0755 root root -"
    ];

    # Generate sanoid.conf using systemd service
    systemd.services.sanoid-config = {
      description = "Generate sanoid configuration";
      # Run early at boot
      wantedBy = [ "multi-user.target" ];
      serviceConfig = {
        Type = "oneshot";
        RemainAfterExit = true;
        ExecStart = let
          script = pkgs.writeShellScript "sanoid-gen-config" ''
            #!/bin/bash
            set -e
            
            # Ensure directory exists
            mkdir -p /etc/sanoid
            
            cat > /etc/sanoid/sanoid.conf << 'EOF'
            # Auto-generated by NixOS - DO NOT EDIT
            
            [tank-fast/appdata]
            	hourly = 24
            	daily = 7
            	monthly = 3
            	yearly = 0
            	recursive = true
            
            # tank/media vive en pool tank (mirror sda+sdb spinning HDDs).
            # Snapshots hourly disparan writes en ambos legs del mirror — en
            # sdb (Toshiba MG07ACA12TE 2026-04 nuevo, con 8 reallocated del
            # infant mortality batch) cada write pasa por sectores marginales
            # → ruido mecánico audible cada hora exacta.
            # Reducción 2026-05-02: hourly 24 → 6 (cada 4h en lugar de cada hora).
            # Pierde granularidad sub-cuatro-horaria pero mantiene cobertura
            # diaria/mensual/yearly intacta. Frigate y Immich son tolerantes
            # a 4h gap (ya hacen sus propios buffers internos).
            [tank/media]
            	hourly = 6
            	daily = 7
            	monthly = 3
            	yearly = 0
            	recursive = true
            
            [tank]
            	daily = 7
            	monthly = 3
            	yearly = 1
            	recursive = false
            EOF
            
            chmod 644 /etc/sanoid/sanoid.conf
          '';
        in script;
      };
    };

    # Enable sanoid.timer for automatic snapshots
    systemd.services.sanoid = {
      description = "Sanoid ZFS Snapshot Management";
      wantedBy = [ "multi-user.target" ];
      # Run config first
      after = [ "sanoid-config.service" ];
      requires = [ "sanoid-config.service" ];
      serviceConfig = {
        ExecStart = "${pkgs.sanoid}/bin/sanoid --take-snapshots";
      };
    };

    systemd.timers.sanoid = {
      description = "Run Sanoid snapshots periodically";
      wantedBy = [ "timers.target" ];
      timerConfig = {
        OnBootSec = "5min";
        OnUnitActiveSec = "1hour";
        RandomizedDelaySec = "15min";
      };
    };
  };
}
